//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackerAUTH
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminder
    {
        public int reminderId { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> reminderDate { get; set; }
        public Nullable<int> taskId { get; set; }
    
        public virtual task task { get; set; }
    }
}
