//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackerAUTH
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskLog
    {
        public int logId { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<int> taskId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
    
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}
