//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackerAUTH
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.reminders = new HashSet<reminder>();
            this.taskLogs = new HashSet<taskLog>();
        }
    
        public int taskId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string priority { get; set; }
        public string status { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<System.Guid> userId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reminder> reminders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskLog> taskLogs { get; set; }
        public virtual user user { get; set; }
    }
}
