//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskTrackerAUTH
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersRole
    {
        public System.Guid userId { get; set; }
        public string fullName { get; set; }
        public string email { get; set; }
        public string passwordHash { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
